os: linux
language: python
python:
  - 2.7
  #  - 3.4
  #  - 3.5
  - 3.6

matrix:
  allow_failures:
    - python: 2.7
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:

  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
  - bash anaconda.sh -b -p $HOME/anaconda > tmp.txt && echo "alive"
  - . /home/travis/anaconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a

  # create env and activate
  - conda create -q -n tfphasespace-env python=$TRAVIS_PYTHON_VERSION root -c conda-forge > tmp.txt && echo "alive"
  - conda activate tfphasespace-env

  # install test environment
  - conda install -y coverage > tmp.txt && echo "alive"
  - conda install -y future > tmp.txt && echo "alive"
  - pip install coveralls > tmp.txt && echo "alive"
  - pip install -r requirements_dev.txt

install:
  - pip install .
  -
script:
  - pytest --cov-branch --cov=tfphasespace tests

after_success:
  - coveralls
#
#deploy:
#  provider: pypi
#  user: zfit
#  password:
#    secure:  TODO
#  distributions: sdist bdist_wheel
#  on:
#    branch: master
#    tag: true
#    condition: $TRAVIS_PYTHON_VERSION = 3.7


