# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unittenst

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -e .[test]
          pip install coverage coveralls

      - name: Download test data
        run: |
          cd data
          python download_test_files.py && cd ..

      - name: Test with pytest
        run: |
          coverage run --branch -m py.test --basetemp={envtmpdir}
          export PHASESPACE_EAGER=1
          coverage run --branch -m py.test --basetemp={envtmpdir}
          export PHASESPACE_EAGER=0  # reset

      - name: Coveralls GitHub Action
        run: |
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
